#! /usr/bin/env bash

TIMEOUT_SECONDS=4

divider="============"
exit="Exit"
back="Back"
refresh="Refresh"
scan="Scanning...."

function echo_nonselectable() {
    echo -en "$1\0nonselectable\x1ftrue\n"
}

function set_status() {
    echo -en "\0message\x1f$1\n"
}

function echoinfo() {
    echo -en "$1\0info\x1f$2\n"
}
function tm() {
    timeout -v $TIMEOUT_SECONDS "$@" # >/dev/null

    echo $?
}

function select_line() {
    echo -en "\0active\x1f$1\n"
}

function is_discoverable() {
    bluetoothctl show | awk -F': ' \
        '$1 ~ /^\sDiscoverable$/ {print "Discoverable:", $2=="no"? "ON" : "OFF" ; if ($2=="no") exit 1 }'
}

function is_powered() {
    bluetoothctl show | awk -F': ' \
        '$1 ~ /^\sPowered$/ {print "Powered:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'
}

function is_scanning() {
    bluetoothctl show | awk -F': ' \
        '$1 ~ /^\sDiscovering$/ {print "Scanning:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'
}

function is_pairable() {
    bluetoothctl show | awk -F': ' \
        '$1 ~ /^\sPairable$/ {print "Pairable:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'
}

function print_devices() {
    devices=$(bluetoothctl devices | awk '{$1=$2="";print $0}')
    while read -r line; do
        d_mac=$(bluetoothctl devices | grep "$line" | awk '{print $2}')
        echoinfo "    $line" "device;;$line"

        i=$((i + 1))
        if is_connected "$d_mac" >/dev/null; then
            select_line $i
        fi
    done <<<"$devices"
}

function is_paired() {
    bluetoothctl info "$1" | awk -F': ' \
        '$1 ~ /^\sPaired$/ {print "Paired:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'
}

function is_connected() {
    bluetoothctl info "$1" | awk -F': ' \
        '$1 ~ /Connected/ {print "Connected:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'

}
function is_trusted() {
    bluetoothctl info "$1" | awk -F': ' \
        '$1 ~ /^\sTrusted$/ {print "Trusted:", $2=="yes"? "ON" : "OFF" ; if ($2=="no") exit 1 }'

}

function toggle_pair() {
    if is_paired "$1" >>/dev/null; then
        tm bluetoothctl remove "$1" >>/dev/null
    else
        tm bluetoothctl pair "$1" >>/dev/null
    fi
}

function toggle_connect() {
    if is_connected "$1" >>/dev/null; then
        tm bluetoothctl disconnect "$1" >>/dev/null
    else
        tm bluetoothctl connect "$1" >>/dev/null
    fi
}

function toggle_trust() {
    if is_trusted "$1" >>/dev/null; then
        tm bluetoothctl untrust "$1" >>/dev/null
    else
        tm bluetoothctl trust "$1" >>/dev/null
    fi
}

function device_state() {
    device=$(echo $ROFI_INFO | cut -d ';' -f3)
    action=$(echo $ROFI_INFO | cut -d ';' -f2)
    mac=$(bluetoothctl devices | grep "$device" | awk '{print $2}')

    case $action in
        "pair")
            toggle_pair "$mac"
            ;;
        "connect")
            toggle_connect "$mac"
            ;;
        "trust")
            toggle_trust "$mac"
            ;;
    esac

    echo -en "\0prompt\x1f$device\n"

    connected=$(is_connected "$mac")
    paired=$(is_paired "$mac")
    trusted=$(is_trusted "$mac")

    echo_nonselectable "Control: "
    echoinfo "    $connected" "device;connect;$device"
    echoinfo "    $paired" "device;pair;$device"
    echoinfo "    $trusted" "device;trust;$device"

    echoinfo "$refresh" "device;;$device"

    echo $back
    echo $exit
}

function toggle_scan() {
    if is_scanning >>/dev/null; then
        kill $(pgrep -f "bluetoothctl scan on")
        tm bluetoothctl scan off >>/dev/null
    else
        tm bluetoothctl scan on >>/dev/null &
    fi
}

function toggle_discoverable() {
    if is_discoverable >>/dev/null; then
        tm bluetoothctl discoverable off >>/dev/null
    else
        tm bluetoothctl discoverable on >>/dev/null
    fi
}

function toggle_powered() {
    if is_powered >>/dev/null; then
        tm bluetoothctl power off >>/dev/null
    else
        tm bluetoothctl power on >>/dev/null
    fi
}

function toggle_pairable() {
    if is_pairable >>/dev/null; then
        tm bluetoothctl pairable off >>/dev/null
    else
        tm bluetoothctl pairable on >>/dev/null
    fi
}

function menu_state() {

    action=$(echo $ROFI_INFO | cut -d ';' -f2)

    case "$action" in
        "exit")
            exit 0
            ;;
        "scan")
            toggle_scan
            ;;
        "discover")
            toggle_discoverable
            ;;
        "power")
            toggle_powered
            ;;

        "pair")
            toggle_pairable
            ;;
    esac

    discoverable=$(is_discoverable)
    powered=$(is_powered)
    scanning=$(is_scanning)
    pairable=$(is_pairable)

    set_status "$powered | $discoverable | $scanning | $pairable"
    echo_nonselectable "Devices: "
    print_devices
    echo_nonselectable "Control: "
    echoinfo "    Refresh" "menu;refresh"
    echoinfo "    Toggle Power" "menu;power"
    echoinfo "    Toggle Discoverable" "menu;discover"
    echoinfo "    Toggle Scan" "menu;scan"
    echoinfo "    Toggle pairable" "menu;pair"
    echoinfo "$exit" "menu;exit"
}

function main() {
    # echo $@ test
    SEL="$*"
    RET=$ROFI_RETV

    # ROFI_INFO stores the information about the state of the app
    # see rofi-script(5)
    # {ROFI_INFO} = {state};{action};{other_info}
    # echoinfo is used to store the action/ state when the user selects an option
    # echoinfo {option_content} {ROFI_INFO}

    state=$(echo $ROFI_INFO | cut -d ';' -f1)

    echo -en "\0prompt\x1f\n"

    if [[ "$state" == "" || "$state" == "menu" ]]; then
        menu_state
    elif [[ "$state" == "device" ]]; then
        device_state $SEL
    fi
}

main $@
