#!/bin/bash

set -euo pipefail

if ! emacsclient -a false --eval nil --quiet >/dev/null 2>&1; then
    echo "Error: Emacs not running." >&2
    exit 1
fi

IS_GRAPHICAL="$(emacsclient -a false --eval "(display-graphic-p)" --quiet)"
ARGS=

if [ "$IS_GRAPHICAL" = "t" ]; then
    ARGS="-nw"
fi

exec emacsclient $ARGS -nw -c --eval "(progn (magit-status) (delete-other-windows))"
